### ISSUE TITLE
运行 example.go 报错

### ISSUE THREAD

**Issue by nujeh** [DeanThompson/zhihu-go#10]
新建了 config.json，增加了登陆信息，运行时，输出了登陆成功，但没有成功执行。报错信息：

```
NFO: GET https://www.zhihu.com/settings/profile
INFO: 获取 profile 的请求，跳转到了：https://www.zhihu.com/?next=%2Fsettings%2Fprofile
INFO: 登录类型：email, 登录地址：https://www.zhihu.com/login/email
INFO: GET https://www.zhihu.com
INFO: 获取验证码：https://www.zhihu.com/captcha.gif?r=1482506116000&type=login
INFO: GET https://www.zhihu.com/captcha.gif?r=1482506116000&type=login
INFO: 调用外部程序渲染验证码……
INFO: Command: open /Users/Frank/src/github.com/DeanThompson/zhihu-go/examples/verify.gif
请输入验证码：vuyx
INFO: 登录中，用户名：**********@hotmail.com
INFO: 登录响应内容：{"r":0, "msg": "\u767b\u5f55\u6210\u529f"}
SUCCESS: 登录成功！
INFO: User fields:
INFO:   is anonymous: false
INFO: GET https://www.zhihu.com/people/jixin
INFO:   userId:
panic: interface conversion: interface is nil, not string

goroutine 1 [running]:
panic(0x2a5f00, 0xc4202a5400)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/DeanThompson/zhihu-go.(*User).GetDataID(0xc4203edc20, 0x2f7589, 0xb)
        /Users/myname/src/github.com/DeanThompson/zhihu-go/user.go:85 +0x3db
main.showUser(0xc4203edc20)
        /Users/myname/src/github.com/DeanThompson/zhihu-go/examples/example.go:164 +0x231
main.main()
        /Users/myname/src/github.com/DeanThompson/zhihu-go/examples/example.go:19 +0x81
exit status 2
```

golang 版本：
go version go1.7.3 darwin/amd64

**Comment by DeanThompson** [comment]
@knarfeh 多谢反馈，知乎的个人主页改版了，我尽快修复。

**Comment by linkerlin** [comment]
SUCCESS: 登录成功！
INFO: User fields:
INFO: 	is anonymous: false
INFO: GET https://www.zhihu.com/people/jixin
INFO: 	userId: 
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
github.com/DeanThompson/zhihu-go.(*User).GetDataID(0xc4201ab4e0, 0x1322783, 0xb)
	/Users/linker/go/src/github.com/DeanThompson/zhihu-go/user.go:85 +0x3fe
main.showUser(0xc4201ab4e0)
	/Users/linker/go/src/github.com/DeanThompson/zhihu-go/examples/example.go:164 +0x227
main.main()
	/Users/linker/go/src/github.com/DeanThompson/zhihu-go/examples/example.go:19 +0x81
exit status 2

我也遇到同样的错误

**Comment by linkerlin** [comment]
json.Unmarshal([]byte(script), &data)
获取到的map是空的。

**Comment by DeanThompson** [comment]
@linkerlin 知乎前端改版了，最近一直没空更新。欢迎提交 PR.
